//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Country
{
    public string ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> SortOder { get; set; }
}

public partial class Membership
{
    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string Password { get; set; }
    public int PasswordFormat { get; set; }
    public string PasswordSalt { get; set; }
    public string Email { get; set; }
    public string PasswordQuestion { get; set; }
    public string PasswordAnswer { get; set; }
    public bool IsApproved { get; set; }
    public bool IsLockedOut { get; set; }
    public System.DateTime CreateDate { get; set; }
    public System.DateTime LastLoginDate { get; set; }
    public System.DateTime LastPasswordChangedDate { get; set; }
    public System.DateTime LastLockoutDate { get; set; }
    public int FailedPasswordAttemptCount { get; set; }
    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    public int FailedPasswordAnswerAttemptCount { get; set; }
    public System.DateTime FailedPasswordAnswerAttemptWindowsStart { get; set; }
    public string Comment { get; set; }

    public virtual User User { get; set; }
}

public partial class PaymentInformation
{
    public int ID { get; set; }
    public string txn_id { get; set; }
    public System.Guid UserId { get; set; }
    public string pay_stat { get; set; }
    public string user_email { get; set; }
    public string custom { get; set; }
    public string InitialInfoSentByPayPal { get; set; }
    public string StrResponse { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
}

public partial class PolinatorInformation
{
    public System.Guid UserId { get; set; }
    public Nullable<bool> IsApproved { get; set; }
    public Nullable<bool> IsPaid { get; set; }
    public bool IsNew { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<System.DateTime> LastUpdated { get; set; }
    public Nullable<System.DateTime> PaidDate { get; set; }
    public Nullable<System.DateTime> ExpireDate { get; set; }
    public string OrganizationName { get; set; }
    public int PollinatorSize { get; set; }
    public string LandscapeStreet { get; set; }
    public string LandscapeCity { get; set; }
    public string LandscapeState { get; set; }
    public string LandscapeZipcode { get; set; }
    public string LandscapeCountry { get; set; }
    public string PhotoUrl { get; set; }
    public string YoutubeUrl { get; set; }
    public string Website { get; set; }
    public int PollinatorType { get; set; }
    public string Description { get; set; }
    public string BillingAddress { get; set; }
    public string BillingCity { get; set; }
    public string BillingState { get; set; }
    public string BillingZipcode { get; set; }
    public string PaymentFullName { get; set; }
    public string PaymentAddress { get; set; }
    public string PaymentState { get; set; }
    public string PaymentCardNumber { get; set; }
    public Nullable<decimal> Latitude { get; set; }
    public Nullable<decimal> Longitude { get; set; }
    public string UserFolder { get; set; }
    public Nullable<bool> FuzyLocation { get; set; }
    public string SourceData { get; set; }

    public virtual PollinatorSize PollinatorSize1 { get; set; }
}

public partial class PollinatorSize
{
    public PollinatorSize()
    {
        this.PolinatorInformations = new HashSet<PolinatorInformation>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    public virtual ICollection<PolinatorInformation> PolinatorInformations { get; set; }
}

public partial class PollinatorType
{
    public int ID { get; set; }
    public string Name { get; set; }
}

public partial class Sponsor
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string PhotoUrl { get; set; }
    public string Website { get; set; }
    public bool IsActive { get; set; }
}

public partial class TempUserPayment
{
    public System.Guid UserId { get; set; }
    public string Email { get; set; }
    public byte MembershipLevel { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string PhoneNumber { get; set; }
    public string OrganizationName { get; set; }
    public int PollinatorSize { get; set; }
    public string LandscapeStreet { get; set; }
    public string LandscapeCity { get; set; }
    public string LandscapeState { get; set; }
    public string LandscapeZipcode { get; set; }
    public string LandscapeCountry { get; set; }
    public string PhotoUrl { get; set; }
    public string YoutubeUrl { get; set; }
    public string Website { get; set; }
    public int PollinatorType { get; set; }
    public string Description { get; set; }
    public string BillingAddress { get; set; }
    public string BillingCity { get; set; }
    public string BillingState { get; set; }
    public string BillingZipcode { get; set; }
    public string PaymentFullName { get; set; }
    public string PaymentAddress { get; set; }
    public string PaymentState { get; set; }
    public string PaymentCardNumber { get; set; }
    public Nullable<decimal> Latitude { get; set; }
    public Nullable<decimal> Longitude { get; set; }
    public string UserFolder { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<int> CreateProcess { get; set; }
    public string PaypalFormHtmlStr { get; set; }
    public string OrganizationName_PollinatorInfomation { get; set; }
}

public partial class User
{
    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string UserName { get; set; }
    public bool IsAnonymous { get; set; }
    public System.DateTime LastActivityDate { get; set; }

    public virtual Membership Membership { get; set; }
}

public partial class UserDetail
{
    public System.Guid UserId { get; set; }
    public Nullable<byte> MembershipLevel { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string PhoneNumber { get; set; }
    public string OrganizationName { get; set; }
}
