//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PollinatorEntities : DbContext
{
    public PollinatorEntities()
        : base("name=PollinatorEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<PollinatorSize> PollinatorSizes { get; set; }
    public DbSet<PollinatorType> PollinatorTypes { get; set; }
    public DbSet<Sponsor> Sponsors { get; set; }
    public DbSet<PaymentInformation> PaymentInformations { get; set; }
    public DbSet<Country> Countries { get; set; }
    public DbSet<TempUserPayment> TempUserPayments { get; set; }
    public DbSet<UserDetail> UserDetails { get; set; }
    public DbSet<Membership> Memberships { get; set; }
    public DbSet<PolinatorInformation> PolinatorInformations { get; set; }
    public DbSet<User> Users { get; set; }
}
