//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollinator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInformation
    {
        public int ID { get; set; }
        public string txn_id { get; set; }
        public System.Guid UserId { get; set; }
        public string pay_stat { get; set; }
        public string user_email { get; set; }
        public string custom { get; set; }
        public string InitialInfoSentByPayPal { get; set; }
        public string StrResponse { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
