//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollinator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolinatorInformation
    {
        public System.Guid UserId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public bool IsNew { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string OrganizationName { get; set; }
        public int PollinatorSize { get; set; }
        public string LandscapeStreet { get; set; }
        public string LandscapeCity { get; set; }
        public string LandscapeState { get; set; }
        public string LandscapeZipcode { get; set; }
        public string LandscapeCountry { get; set; }
        public string PhotoUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string Website { get; set; }
        public int PollinatorType { get; set; }
        public string Description { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZipcode { get; set; }
        public string PaymentFullName { get; set; }
        public string PaymentAddress { get; set; }
        public string PaymentState { get; set; }
        public string PaymentCardNumber { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string UserFolder { get; set; }
        public Nullable<bool> FuzyLocation { get; set; }
        public string SourceData { get; set; }
    
        public virtual PollinatorSize PollinatorSize1 { get; set; }
    }
}
