//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollinator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollinatorSize
    {
        public PollinatorSize()
        {
            this.PolinatorInformations = new HashSet<PolinatorInformation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PolinatorInformation> PolinatorInformations { get; set; }
    }
}
