//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollinator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PhotoUrl { get; set; }
        public string Website { get; set; }
        public bool IsActive { get; set; }
    }
}
