//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollinator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserPayment
    {
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public byte MembershipLevel { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string OrganizationName { get; set; }
        public int PollinatorSize { get; set; }
        public string LandscapeStreet { get; set; }
        public string LandscapeCity { get; set; }
        public string LandscapeState { get; set; }
        public string LandscapeZipcode { get; set; }
        public string LandscapeCountry { get; set; }
        public string PhotoUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string Website { get; set; }
        public int PollinatorType { get; set; }
        public string Description { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZipcode { get; set; }
        public string PaymentFullName { get; set; }
        public string PaymentAddress { get; set; }
        public string PaymentState { get; set; }
        public string PaymentCardNumber { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string UserFolder { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateProcess { get; set; }
        public string PaypalFormHtmlStr { get; set; }
        public string OrganizationName_PollinatorInfomation { get; set; }
    }
}
