//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollinator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public System.Guid UserId { get; set; }
        public Nullable<byte> MembershipLevel { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string OrganizationName { get; set; }
    }
}
